import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FiChevronDown } from "react-icons/fi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-300">
        {/* NAVBAR */}
        <nav className="flex justify-center mt-3 my-1.5">
            <p className="hidden lg:block absolute left-0 ml-12 py-2">ao</p>
            <ul className="flex flex-nowrap justify-center p-4 sm:py-1.5 bg-white rounded-md xl:gap-x-30 lg:gap-x-24 md:gap-x-16 sm:gap-x-12 gap-x-6 w-full xl:max-w-5xl lg:max-w-4xl md:max-w-2xl sm:max-w-xl max-w-lg tracking-wider mx-4">
                
                <li className="relative group hover:text-gray-300 text-gray-400 hidden sm:flex items-center cursor-pointer">
                    <span className="flex items-center">
                        dsfdsf
                        <FiChevronDown className="ml-2" />
                    </span>
                    
                    <div className="absolute top-full -left-2 mt-2 hidden group-hover:flex flex-col min-2-[160px] z-50">
                        <a href="/" className="px-3 py-2 text-white">
                            jejejej
                        </a>
                        <a href="/" className="px-3 text-white">
                            jejejej
                        </a>
                    </div>
                </li>
                
                <li className="relative group hover:text-gray-300 text-gray-400 hidden sm:flex items-center cursor-pointer">
                    <span className="flex items-center">
                        dsfdsf
                        <FiChevronDown className="ml-2" />
                    </span>
                    
                    <div className="absolute top-full -left-2 mt-2 hidden group-hover:flex flex-col min-2-[160px] z-50">
                        <a href="/" className="px-3 py-2 text-white">
                            jejejej
                        </a>
                        <a href="/" className="px-3 text-white">
                            jejejej
                        </a>
                    </div>
                </li>
                
                <li className="hover:text-gray-300 text-gray-400 hidden sm:flex items-center cursor-pointer">
                    dsfdsf
                </li>
            </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
